version: '3.8'

services:
  prices-service:
    image: innoqa/prices:latest
    build:
      context: ./
      dockerfile: ./src/main/docker/Dockerfile
    restart: always
    container_name: prices-service
    hostname: prices-service
    ports:
      - '8080:8080'
    networks:
      - 'dockernetflix-network'
    environment:
      TZ: Africa/Abidjan
      hostName: prices-service
networks:
  dockernetflix-network: #necesitamos crear en una red para alojar los servicios en ella y que puedan comunicarse entre sí
